package com.torkirion.eroam.microservice.accommodation.endpoint.youtravel;

import com.torkirion.eroam.HttpService;
import lombok.extern.slf4j.Slf4j;
import org.apache.http.HttpMessage;

@Slf4j
public class YoutravelHttpService extends HttpService
{
	private YoutravelAPIProperties youtravelProperties;
	
	public YoutravelHttpService(YoutravelAPIProperties youtravelProperties)
	{
		this.youtravelProperties = youtravelProperties;
	}
	
	@Override
	protected void addHeaders(HttpMessage httpMessage)
	{
		// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
		String hexkey = youtravelProperties.apikey + youtravelProperties.secret + System.currentTimeMillis() / 1000;
		String signature = org.apache.commons.codec.digest.DigestUtils.sha256Hex(hexkey);
		log.debug("addHeaders::submitting signature '" + signature + "' from hexKey '" + hexkey + "' and apikey/secret " + youtravelProperties.apikey + "/" + youtravelProperties.secret);

		httpMessage.setHeader("X-Signature", signature);
		httpMessage.setHeader("Api-Key", youtravelProperties.apikey);
		httpMessage.setHeader("Accept", "application/xml");
		httpMessage.setHeader("Accept-Encoding", "gzip, deflate");
		httpMessage.setHeader("Content-Type", "application/xml; charset=UTF-8");
	}

	@Override
	protected String getUrl()
	{
		return youtravelProperties.youtravelURL;
	}
}
