//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 10:00:19 PM ICT 
//


package com.sabre.schema.hotel.pricecheck.v4_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.sabre.schema.stl_payload.v02_02.STLRequestPayload;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://services.sabre.com/STL_Payload/v02_02}STL_Request_Payload"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="POS" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}POS" minOccurs="0"/&gt;
 *         &lt;element name="RateInfoRef" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}RateInfoRef"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pos",
    "rateInfoRef"
})
@XmlRootElement(name = "HotelPriceCheckRQ")
public class HotelPriceCheckRQ
    extends STLRequestPayload
{

    @XmlElement(name = "POS")
    protected POS pos;
    @XmlElement(name = "RateInfoRef", required = true)
    protected RateInfoRef rateInfoRef;

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link POS }
     *     
     */
    public POS getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link POS }
     *     
     */
    public void setPOS(POS value) {
        this.pos = value;
    }

    /**
     * Gets the value of the rateInfoRef property.
     * 
     * @return
     *     possible object is
     *     {@link RateInfoRef }
     *     
     */
    public RateInfoRef getRateInfoRef() {
        return rateInfoRef;
    }

    /**
     * Sets the value of the rateInfoRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateInfoRef }
     *     
     */
    public void setRateInfoRef(RateInfoRef value) {
        this.rateInfoRef = value;
    }

}
