//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 10:00:19 PM ICT 
//


package com.sabre.schema.hotel.pricecheck.v4_0_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Describes latest information for chosen product along with any observed changes in rates.
 *             
 * 
 * <p>Java class for PriceCheckInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceCheckInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HotelInfo" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}HotelInfo"/&gt;
 *         &lt;element name="HotelRateInfo" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}HotelRateInfo"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="BookingKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PriceChange" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="PriceDifference" use="required" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}PriceDifferenceAmount" /&gt;
 *       &lt;attribute name="CurrencyCode" use="required" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}StringLength3WithNoSpace" /&gt;
 *       &lt;attribute name="ConvertedPriceChange" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="ConvertedPriceDifference" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}PriceDifferenceAmount" /&gt;
 *       &lt;attribute name="ConvertedCurrencyCode" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}StringLength3WithNoSpace" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceCheckInfo", propOrder = {
    "hotelInfo",
    "hotelRateInfo"
})
public class PriceCheckInfo {

    @XmlElement(name = "HotelInfo", required = true)
    protected HotelInfo hotelInfo;
    @XmlElement(name = "HotelRateInfo", required = true)
    protected HotelRateInfo hotelRateInfo;
    @XmlAttribute(name = "BookingKey", required = true)
    protected String bookingKey;
    @XmlAttribute(name = "PriceChange", required = true)
    protected boolean priceChange;
    @XmlAttribute(name = "PriceDifference", required = true)
    protected BigDecimal priceDifference;
    @XmlAttribute(name = "CurrencyCode", required = true)
    protected String currencyCode;
    @XmlAttribute(name = "ConvertedPriceChange")
    protected Boolean convertedPriceChange;
    @XmlAttribute(name = "ConvertedPriceDifference")
    protected BigDecimal convertedPriceDifference;
    @XmlAttribute(name = "ConvertedCurrencyCode")
    protected String convertedCurrencyCode;

    /**
     * Gets the value of the hotelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HotelInfo }
     *     
     */
    public HotelInfo getHotelInfo() {
        return hotelInfo;
    }

    /**
     * Sets the value of the hotelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelInfo }
     *     
     */
    public void setHotelInfo(HotelInfo value) {
        this.hotelInfo = value;
    }

    /**
     * Gets the value of the hotelRateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HotelRateInfo }
     *     
     */
    public HotelRateInfo getHotelRateInfo() {
        return hotelRateInfo;
    }

    /**
     * Sets the value of the hotelRateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelRateInfo }
     *     
     */
    public void setHotelRateInfo(HotelRateInfo value) {
        this.hotelRateInfo = value;
    }

    /**
     * Gets the value of the bookingKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingKey() {
        return bookingKey;
    }

    /**
     * Sets the value of the bookingKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingKey(String value) {
        this.bookingKey = value;
    }

    /**
     * Gets the value of the priceChange property.
     * 
     */
    public boolean isPriceChange() {
        return priceChange;
    }

    /**
     * Sets the value of the priceChange property.
     * 
     */
    public void setPriceChange(boolean value) {
        this.priceChange = value;
    }

    /**
     * Gets the value of the priceDifference property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceDifference() {
        return priceDifference;
    }

    /**
     * Sets the value of the priceDifference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceDifference(BigDecimal value) {
        this.priceDifference = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the convertedPriceChange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConvertedPriceChange() {
        return convertedPriceChange;
    }

    /**
     * Sets the value of the convertedPriceChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConvertedPriceChange(Boolean value) {
        this.convertedPriceChange = value;
    }

    /**
     * Gets the value of the convertedPriceDifference property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConvertedPriceDifference() {
        return convertedPriceDifference;
    }

    /**
     * Sets the value of the convertedPriceDifference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConvertedPriceDifference(BigDecimal value) {
        this.convertedPriceDifference = value;
    }

    /**
     * Gets the value of the convertedCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvertedCurrencyCode() {
        return convertedCurrencyCode;
    }

    /**
     * Sets the value of the convertedCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvertedCurrencyCode(String value) {
        this.convertedCurrencyCode = value;
    }

}
