//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 10:00:19 PM ICT 
//


package com.sabre.schema.hotel.pricecheck.v4_0_0;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Rate Info associated with a particular Room Stay
 * 
 * <p>Java class for RateInfoTypeForRoom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateInfoTypeForRoom"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Rates" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded"&gt;
 *                   &lt;element name="Rate"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="StartDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
 *                           &lt;attribute name="EndDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
 *                           &lt;attribute name="AmountBeforeTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
 *                           &lt;attribute name="AmountAfterTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
 *                           &lt;attribute name="CurrencyCode" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}StringLength3WithNoSpace" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Taxes" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}RateTaxesType" minOccurs="0"/&gt;
 *         &lt;element name="Fees" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}RateFeesType" minOccurs="0"/&gt;
 *         &lt;element name="RoomExtras" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}RoomExtrasType" minOccurs="0"/&gt;
 *         &lt;element name="CancelPenalties" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}CancelPenaltiesType"/&gt;
 *         &lt;element name="Guarantee" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}GuaranteeType" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalDetails" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}AdditionalDetails" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="StartDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
 *       &lt;attribute name="EndDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
 *       &lt;attribute name="AmountBeforeTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
 *       &lt;attribute name="AmountAfterTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
 *       &lt;attribute name="MinSellingRate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
 *       &lt;attribute name="AverageNightlyRate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
 *       &lt;attribute name="AverageNightlyRateBeforeTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
 *       &lt;attribute name="CurrencyCode" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}StringLength3WithNoSpace" /&gt;
 *       &lt;attribute name="AdditionalFeesInclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="TaxInclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="LocalFeesInclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="IncidentalsInclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "checkRate", name = "RateInfoTypeForRoom", propOrder = {
    "rates",
    "taxes",
    "fees",
    "roomExtras",
    "cancelPenalties",
    "guarantee",
    "additionalDetails"
})
public class RateInfoTypeForRoom {

    @XmlElement(name = "Rates")
    protected RateInfoTypeForRoom.Rates rates;
    @XmlElement(name = "Taxes")
    protected RateTaxesType taxes;
    @XmlElement(name = "Fees")
    protected RateFeesType fees;
    @XmlElement(name = "RoomExtras")
    protected RoomExtrasType roomExtras;
    @XmlElement(name = "CancelPenalties", required = true)
    protected CancelPenaltiesType cancelPenalties;
    @XmlElement(name = "Guarantee")
    protected GuaranteeType guarantee;
    @XmlElement(name = "AdditionalDetails")
    protected AdditionalDetails additionalDetails;
    @XmlAttribute(name = "StartDate")
    protected XMLGregorianCalendar startDate;
    @XmlAttribute(name = "EndDate")
    protected XMLGregorianCalendar endDate;
    @XmlAttribute(name = "AmountBeforeTax")
    protected BigDecimal amountBeforeTax;
    @XmlAttribute(name = "AmountAfterTax")
    protected BigDecimal amountAfterTax;
    @XmlAttribute(name = "MinSellingRate")
    protected BigDecimal minSellingRate;
    @XmlAttribute(name = "AverageNightlyRate")
    protected BigDecimal averageNightlyRate;
    @XmlAttribute(name = "AverageNightlyRateBeforeTax")
    protected BigDecimal averageNightlyRateBeforeTax;
    @XmlAttribute(name = "CurrencyCode")
    protected String currencyCode;
    @XmlAttribute(name = "AdditionalFeesInclusive")
    protected Boolean additionalFeesInclusive;
    @XmlAttribute(name = "TaxInclusive")
    protected Boolean taxInclusive;
    @XmlAttribute(name = "LocalFeesInclusive")
    protected Boolean localFeesInclusive;
    @XmlAttribute(name = "IncidentalsInclusive")
    protected Boolean incidentalsInclusive;

    /**
     * Gets the value of the rates property.
     * 
     * @return
     *     possible object is
     *     {@link RateInfoTypeForRoom.Rates }
     *     
     */
    public RateInfoTypeForRoom.Rates getRates() {
        return rates;
    }

    /**
     * Sets the value of the rates property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateInfoTypeForRoom.Rates }
     *     
     */
    public void setRates(RateInfoTypeForRoom.Rates value) {
        this.rates = value;
    }

    /**
     * Gets the value of the taxes property.
     * 
     * @return
     *     possible object is
     *     {@link RateTaxesType }
     *     
     */
    public RateTaxesType getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateTaxesType }
     *     
     */
    public void setTaxes(RateTaxesType value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link RateFeesType }
     *     
     */
    public RateFeesType getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateFeesType }
     *     
     */
    public void setFees(RateFeesType value) {
        this.fees = value;
    }

    /**
     * Gets the value of the roomExtras property.
     * 
     * @return
     *     possible object is
     *     {@link RoomExtrasType }
     *     
     */
    public RoomExtrasType getRoomExtras() {
        return roomExtras;
    }

    /**
     * Sets the value of the roomExtras property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomExtrasType }
     *     
     */
    public void setRoomExtras(RoomExtrasType value) {
        this.roomExtras = value;
    }

    /**
     * Gets the value of the cancelPenalties property.
     * 
     * @return
     *     possible object is
     *     {@link CancelPenaltiesType }
     *     
     */
    public CancelPenaltiesType getCancelPenalties() {
        return cancelPenalties;
    }

    /**
     * Sets the value of the cancelPenalties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelPenaltiesType }
     *     
     */
    public void setCancelPenalties(CancelPenaltiesType value) {
        this.cancelPenalties = value;
    }

    /**
     * Gets the value of the guarantee property.
     * 
     * @return
     *     possible object is
     *     {@link GuaranteeType }
     *     
     */
    public GuaranteeType getGuarantee() {
        return guarantee;
    }

    /**
     * Sets the value of the guarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuaranteeType }
     *     
     */
    public void setGuarantee(GuaranteeType value) {
        this.guarantee = value;
    }

    /**
     * Gets the value of the additionalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDetails }
     *     
     */
    public AdditionalDetails getAdditionalDetails() {
        return additionalDetails;
    }

    /**
     * Sets the value of the additionalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDetails }
     *     
     */
    public void setAdditionalDetails(AdditionalDetails value) {
        this.additionalDetails = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the amountBeforeTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountBeforeTax() {
        return amountBeforeTax;
    }

    /**
     * Sets the value of the amountBeforeTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountBeforeTax(BigDecimal value) {
        this.amountBeforeTax = value;
    }

    /**
     * Gets the value of the amountAfterTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountAfterTax() {
        return amountAfterTax;
    }

    /**
     * Sets the value of the amountAfterTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountAfterTax(BigDecimal value) {
        this.amountAfterTax = value;
    }

    /**
     * Gets the value of the minSellingRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinSellingRate() {
        return minSellingRate;
    }

    /**
     * Sets the value of the minSellingRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinSellingRate(BigDecimal value) {
        this.minSellingRate = value;
    }

    /**
     * Gets the value of the averageNightlyRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAverageNightlyRate() {
        return averageNightlyRate;
    }

    /**
     * Sets the value of the averageNightlyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAverageNightlyRate(BigDecimal value) {
        this.averageNightlyRate = value;
    }

    /**
     * Gets the value of the averageNightlyRateBeforeTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAverageNightlyRateBeforeTax() {
        return averageNightlyRateBeforeTax;
    }

    /**
     * Sets the value of the averageNightlyRateBeforeTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAverageNightlyRateBeforeTax(BigDecimal value) {
        this.averageNightlyRateBeforeTax = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the additionalFeesInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdditionalFeesInclusive() {
        return additionalFeesInclusive;
    }

    /**
     * Sets the value of the additionalFeesInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdditionalFeesInclusive(Boolean value) {
        this.additionalFeesInclusive = value;
    }

    /**
     * Gets the value of the taxInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxInclusive() {
        return taxInclusive;
    }

    /**
     * Sets the value of the taxInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxInclusive(Boolean value) {
        this.taxInclusive = value;
    }

    /**
     * Gets the value of the localFeesInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocalFeesInclusive() {
        return localFeesInclusive;
    }

    /**
     * Sets the value of the localFeesInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalFeesInclusive(Boolean value) {
        this.localFeesInclusive = value;
    }

    /**
     * Gets the value of the incidentalsInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncidentalsInclusive() {
        return incidentalsInclusive;
    }

    /**
     * Sets the value of the incidentalsInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncidentalsInclusive(Boolean value) {
        this.incidentalsInclusive = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded"&gt;
     *         &lt;element name="Rate"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="StartDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
     *                 &lt;attribute name="EndDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
     *                 &lt;attribute name="AmountBeforeTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
     *                 &lt;attribute name="AmountAfterTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
     *                 &lt;attribute name="CurrencyCode" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}StringLength3WithNoSpace" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rates"
    })
    public static class Rates {

        @XmlElement(name = "Rate", required = true)
        protected List<RateInfoTypeForRoom.Rates.Rate> rates;

        /**
         * Gets the value of the rates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RateInfoTypeForRoom.Rates.Rate }
         * 
         * 
         */
        public List<RateInfoTypeForRoom.Rates.Rate> getRates() {
            if (rates == null) {
                rates = new ArrayList<RateInfoTypeForRoom.Rates.Rate>();
            }
            return this.rates;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="StartDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
         *       &lt;attribute name="EndDate" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Date" /&gt;
         *       &lt;attribute name="AmountBeforeTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
         *       &lt;attribute name="AmountAfterTax" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}Amount" /&gt;
         *       &lt;attribute name="CurrencyCode" type="{http://services.sabre.com/hotel/pricecheck/v4_0_0}StringLength3WithNoSpace" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Rate {

            @XmlAttribute(name = "StartDate")
            protected XMLGregorianCalendar startDate;
            @XmlAttribute(name = "EndDate")
            protected XMLGregorianCalendar endDate;
            @XmlAttribute(name = "AmountBeforeTax")
            protected BigDecimal amountBeforeTax;
            @XmlAttribute(name = "AmountAfterTax")
            protected BigDecimal amountAfterTax;
            @XmlAttribute(name = "CurrencyCode")
            protected String currencyCode;

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setStartDate(XMLGregorianCalendar value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEndDate(XMLGregorianCalendar value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the amountBeforeTax property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAmountBeforeTax() {
                return amountBeforeTax;
            }

            /**
             * Sets the value of the amountBeforeTax property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAmountBeforeTax(BigDecimal value) {
                this.amountBeforeTax = value;
            }

            /**
             * Gets the value of the amountAfterTax property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAmountAfterTax() {
                return amountAfterTax;
            }

            /**
             * Sets the value of the amountAfterTax property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAmountAfterTax(BigDecimal value) {
                this.amountAfterTax = value;
            }

            /**
             * Gets the value of the currencyCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrencyCode() {
                return currencyCode;
            }

            /**
             * Sets the value of the currencyCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrencyCode(String value) {
                this.currencyCode = value;
            }

        }

    }

}
