//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.11 at 11:37:11 am ICT 
//


package com.hotelbeds.schemas.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filterSelector complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filterSelector">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="minRate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxRate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minCategory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxCategory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxRatesPerRoom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="packaging" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hotelPackage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxRooms" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterSelector")
public class FilterSelector {

    @XmlAttribute
    protected String minRate;
    @XmlAttribute
    protected String maxRate;
    @XmlAttribute
    protected String minCategory;
    @XmlAttribute
    protected String maxCategory;
    @XmlAttribute
    protected String paymentType;
    @XmlAttribute
    protected String maxRatesPerRoom;
    @XmlAttribute
    protected String packaging;
    @XmlAttribute
    protected String hotelPackage;
    @XmlAttribute
    protected String maxRooms;

    /**
     * Gets the value of the minRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinRate() {
        return minRate;
    }

    /**
     * Sets the value of the minRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinRate(String value) {
        this.minRate = value;
    }

    /**
     * Gets the value of the maxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxRate() {
        return maxRate;
    }

    /**
     * Sets the value of the maxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxRate(String value) {
        this.maxRate = value;
    }

    /**
     * Gets the value of the minCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinCategory() {
        return minCategory;
    }

    /**
     * Sets the value of the minCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinCategory(String value) {
        this.minCategory = value;
    }

    /**
     * Gets the value of the maxCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxCategory() {
        return maxCategory;
    }

    /**
     * Sets the value of the maxCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxCategory(String value) {
        this.maxCategory = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the maxRatesPerRoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxRatesPerRoom() {
        return maxRatesPerRoom;
    }

    /**
     * Sets the value of the maxRatesPerRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxRatesPerRoom(String value) {
        this.maxRatesPerRoom = value;
    }

    /**
     * Gets the value of the packaging property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackaging() {
        return packaging;
    }

    /**
     * Sets the value of the packaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackaging(String value) {
        this.packaging = value;
    }

    /**
     * Gets the value of the hotelPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelPackage() {
        return hotelPackage;
    }

    /**
     * Sets the value of the hotelPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelPackage(String value) {
        this.hotelPackage = value;
    }

    /**
     * Gets the value of the maxRooms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxRooms() {
        return maxRooms;
    }

    /**
     * Sets the value of the maxRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxRooms(String value) {
        this.maxRooms = value;
    }

}
