//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.11 at 11:37:11 am ICT 
//


package com.hotelbeds.schemas.messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hotelbeds.schemas.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hotelbeds.schemas.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GroupCategories }
     * 
     */
    public GroupCategories createGroupCategories() {
        return new GroupCategories();
    }

    /**
     * Create an instance of {@link RatesHotelResponse }
     * 
     */
    public RatesHotelResponse createRatesHotelResponse() {
        return new RatesHotelResponse();
    }

    /**
     * Create an instance of {@link RateBreakDown }
     * 
     */
    public RateBreakDown createRateBreakDown() {
        return new RateBreakDown();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Wildcard }
     * 
     */
    public Wildcard createWildcard() {
        return new Wildcard();
    }

    /**
     * Create an instance of {@link RoomStays }
     * 
     */
    public RoomStays createRoomStays() {
        return new RoomStays();
    }

    /**
     * Create an instance of {@link RoomsBookingResponse }
     * 
     */
    public RoomsBookingResponse createRoomsBookingResponse() {
        return new RoomsBookingResponse();
    }

    /**
     * Create an instance of {@link Chains }
     * 
     */
    public Chains createChains() {
        return new Chains();
    }

    /**
     * Create an instance of {@link CancellationPolicies }
     * 
     */
    public CancellationPolicies createCancellationPolicies() {
        return new CancellationPolicies();
    }

    /**
     * Create an instance of {@link PaymentCard }
     * 
     */
    public PaymentCard createPaymentCard() {
        return new PaymentCard();
    }

    /**
     * Create an instance of {@link RateComments }
     * 
     */
    public RateComments createRateComments() {
        return new RateComments();
    }

    /**
     * Create an instance of {@link InterestPoints }
     * 
     */
    public InterestPoints createInterestPoints() {
        return new InterestPoints();
    }

    /**
     * Create an instance of {@link SupplierBookingResponse }
     * 
     */
    public SupplierBookingResponse createSupplierBookingResponse() {
        return new SupplierBookingResponse();
    }

    /**
     * Create an instance of {@link HotelsResponse }
     * 
     */
    public HotelsResponse createHotelsResponse() {
        return new HotelsResponse();
    }

    /**
     * Create an instance of {@link Promotions }
     * 
     */
    public Promotions createPromotions() {
        return new Promotions();
    }

    /**
     * Create an instance of {@link BookingCancellationRS }
     * 
     */
    public BookingCancellationRS createBookingCancellationRS() {
        return new BookingCancellationRS();
    }

    /**
     * Create an instance of {@link HotelSelector }
     * 
     */
    public HotelSelector createHotelSelector() {
        return new HotelSelector();
    }

    /**
     * Create an instance of {@link Facilities }
     * 
     */
    public Facilities createFacilities() {
        return new Facilities();
    }

    /**
     * Create an instance of {@link FilterSelector }
     * 
     */
    public FilterSelector createFilterSelector() {
        return new FilterSelector();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link AuditData }
     * 
     */
    public AuditData createAuditData() {
        return new AuditData();
    }

    /**
     * Create an instance of {@link TerminalsRS }
     * 
     */
    public TerminalsRS createTerminalsRS() {
        return new TerminalsRS();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link KeywordSelector }
     * 
     */
    public KeywordSelector createKeywordSelector() {
        return new KeywordSelector();
    }

    /**
     * Create an instance of {@link GeolocationSelector }
     * 
     */
    public GeolocationSelector createGeolocationSelector() {
        return new GeolocationSelector();
    }

    /**
     * Create an instance of {@link CategoriesRS }
     * 
     */
    public CategoriesRS createCategoriesRS() {
        return new CategoriesRS();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Hotels }
     * 
     */
    public Hotels createHotels() {
        return new Hotels();
    }

    /**
     * Create an instance of {@link HotelResponse }
     * 
     */
    public HotelResponse createHotelResponse() {
        return new HotelResponse();
    }

    /**
     * Create an instance of {@link Terminals }
     * 
     */
    public Terminals createTerminals() {
        return new Terminals();
    }

    /**
     * Create an instance of {@link HotelsRS }
     * 
     */
    public HotelsRS createHotelsRS() {
        return new HotelsRS();
    }

    /**
     * Create an instance of {@link RateSupplement }
     * 
     */
    public RateSupplement createRateSupplement() {
        return new RateSupplement();
    }

    /**
     * Create an instance of {@link RoomHotelResponse }
     * 
     */
    public RoomHotelResponse createRoomHotelResponse() {
        return new RoomHotelResponse();
    }

    /**
     * Create an instance of {@link StaySelector }
     * 
     */
    public StaySelector createStaySelector() {
        return new StaySelector();
    }

    /**
     * Create an instance of {@link PaxSelector }
     * 
     */
    public PaxSelector createPaxSelector() {
        return new PaxSelector();
    }

    /**
     * Create an instance of {@link RoomsBookingRequest }
     * 
     */
    public RoomsBookingRequest createRoomsBookingRequest() {
        return new RoomsBookingRequest();
    }

    /**
     * Create an instance of {@link Hotel }
     * 
     */
    public Hotel createHotel() {
        return new Hotel();
    }

    /**
     * Create an instance of {@link BoardsRS }
     * 
     */
    public BoardsRS createBoardsRS() {
        return new BoardsRS();
    }

    /**
     * Create an instance of {@link RateCommentsRS }
     * 
     */
    public RateCommentsRS createRateCommentsRS() {
        return new RateCommentsRS();
    }

    /**
     * Create an instance of {@link RoomBookingResponse }
     * 
     */
    public RoomBookingResponse createRoomBookingResponse() {
        return new RoomBookingResponse();
    }

    /**
     * Create an instance of {@link GroupCategory }
     * 
     */
    public GroupCategory createGroupCategory() {
        return new GroupCategory();
    }

    /**
     * Create an instance of {@link SegmentCodes }
     * 
     */
    public SegmentCodes createSegmentCodes() {
        return new SegmentCodes();
    }

    /**
     * Create an instance of {@link Issues }
     * 
     */
    public Issues createIssues() {
        return new Issues();
    }

    /**
     * Create an instance of {@link BookingRQ }
     * 
     */
    public BookingRQ createBookingRQ() {
        return new BookingRQ();
    }

    /**
     * Create an instance of {@link ReviewSelector }
     * 
     */
    public ReviewSelector createReviewSelector() {
        return new ReviewSelector();
    }

    /**
     * Create an instance of {@link CheckRateRS }
     * 
     */
    public CheckRateRS createCheckRateRS() {
        return new CheckRateRS();
    }

    /**
     * Create an instance of {@link IssuesRS }
     * 
     */
    public IssuesRS createIssuesRS() {
        return new IssuesRS();
    }

    /**
     * Create an instance of {@link ModificationPolicies }
     * 
     */
    public ModificationPolicies createModificationPolicies() {
        return new ModificationPolicies();
    }

    /**
     * Create an instance of {@link RoomFacilities }
     * 
     */
    public RoomFacilities createRoomFacilities() {
        return new RoomFacilities();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

    /**
     * Create an instance of {@link Phones }
     * 
     */
    public Phones createPhones() {
        return new Phones();
    }

    /**
     * Create an instance of {@link RatePromotions }
     * 
     */
    public RatePromotions createRatePromotions() {
        return new RatePromotions();
    }

    /**
     * Create an instance of {@link RoomsRS }
     * 
     */
    public RoomsRS createRoomsRS() {
        return new RoomsRS();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Wildcards }
     * 
     */
    public Wildcards createWildcards() {
        return new Wildcards();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link Offers }
     * 
     */
    public Offers createOffers() {
        return new Offers();
    }

    /**
     * Create an instance of {@link Accommodations }
     * 
     */
    public Accommodations createAccommodations() {
        return new Accommodations();
    }

    /**
     * Create an instance of {@link DestinationsRS }
     * 
     */
    public DestinationsRS createDestinationsRS() {
        return new DestinationsRS();
    }

    /**
     * Create an instance of {@link BookingDetailRS }
     * 
     */
    public BookingDetailRS createBookingDetailRS() {
        return new BookingDetailRS();
    }

    /**
     * Create an instance of {@link RoomBookingRequest }
     * 
     */
    public RoomBookingRequest createRoomBookingRequest() {
        return new RoomBookingRequest();
    }

    /**
     * Create an instance of {@link HotelIssues }
     * 
     */
    public HotelIssues createHotelIssues() {
        return new HotelIssues();
    }

    /**
     * Create an instance of {@link CommentsByRates }
     * 
     */
    public CommentsByRates createCommentsByRates() {
        return new CommentsByRates();
    }

    /**
     * Create an instance of {@link OccupancySelector }
     * 
     */
    public OccupancySelector createOccupancySelector() {
        return new OccupancySelector();
    }

    /**
     * Create an instance of {@link FacilityTypologiesRS }
     * 
     */
    public FacilityTypologiesRS createFacilityTypologiesRS() {
        return new FacilityTypologiesRS();
    }

    /**
     * Create an instance of {@link RoomsCheckrateRequest }
     * 
     */
    public RoomsCheckrateRequest createRoomsCheckrateRequest() {
        return new RoomsCheckrateRequest();
    }

    /**
     * Create an instance of {@link BoardCodes }
     * 
     */
    public BoardCodes createBoardCodes() {
        return new BoardCodes();
    }

    /**
     * Create an instance of {@link RoomStay }
     * 
     */
    public RoomStay createRoomStay() {
        return new RoomStay();
    }

    /**
     * Create an instance of {@link Destination }
     * 
     */
    public Destination createDestination() {
        return new Destination();
    }

    /**
     * Create an instance of {@link PromotionsRS }
     * 
     */
    public PromotionsRS createPromotionsRS() {
        return new PromotionsRS();
    }

    /**
     * Create an instance of {@link SegmentsRS }
     * 
     */
    public SegmentsRS createSegmentsRS() {
        return new SegmentsRS();
    }

    /**
     * Create an instance of {@link RoomStatic }
     * 
     */
    public RoomStatic createRoomStatic() {
        return new RoomStatic();
    }

    /**
     * Create an instance of {@link RateSupplements }
     * 
     */
    public RateSupplements createRateSupplements() {
        return new RateSupplements();
    }

    /**
     * Create an instance of {@link FacilityTypologies }
     * 
     */
    public FacilityTypologies createFacilityTypologies() {
        return new FacilityTypologies();
    }

    /**
     * Create an instance of {@link PaymentData }
     * 
     */
    public PaymentData createPaymentData() {
        return new PaymentData();
    }

    /**
     * Create an instance of {@link FacilitiesRS }
     * 
     */
    public FacilitiesRS createFacilitiesRS() {
        return new FacilitiesRS();
    }

    /**
     * Create an instance of {@link GroupCategoriesRS }
     * 
     */
    public GroupCategoriesRS createGroupCategoriesRS() {
        return new GroupCategoriesRS();
    }

    /**
     * Create an instance of {@link ImageTypes }
     * 
     */
    public ImageTypes createImageTypes() {
        return new ImageTypes();
    }

    /**
     * Create an instance of {@link Zone }
     * 
     */
    public Zone createZone() {
        return new Zone();
    }

    /**
     * Create an instance of {@link Promotion }
     * 
     */
    public Promotion createPromotion() {
        return new Promotion();
    }

    /**
     * Create an instance of {@link ImageTypesRS }
     * 
     */
    public ImageTypesRS createImageTypesRS() {
        return new ImageTypesRS();
    }

    /**
     * Create an instance of {@link AvailabilityRS }
     * 
     */
    public AvailabilityRS createAvailabilityRS() {
        return new AvailabilityRS();
    }

    /**
     * Create an instance of {@link Facility }
     * 
     */
    public Facility createFacility() {
        return new Facility();
    }

    /**
     * Create an instance of {@link PaxesSelector }
     * 
     */
    public PaxesSelector createPaxesSelector() {
        return new PaxesSelector();
    }

    /**
     * Create an instance of {@link RoomsHotelResponse }
     * 
     */
    public RoomsHotelResponse createRoomsHotelResponse() {
        return new RoomsHotelResponse();
    }

    /**
     * Create an instance of {@link BoardSelector }
     * 
     */
    public BoardSelector createBoardSelector() {
        return new BoardSelector();
    }

    /**
     * Create an instance of {@link Terminal }
     * 
     */
    public Terminal createTerminal() {
        return new Terminal();
    }

    /**
     * Create an instance of {@link ContactData }
     * 
     */
    public ContactData createContactData() {
        return new ContactData();
    }

    /**
     * Create an instance of {@link AccommodationsRS }
     * 
     */
    public AccommodationsRS createAccommodationsRS() {
        return new AccommodationsRS();
    }

    /**
     * Create an instance of {@link FacilityTypology }
     * 
     */
    public FacilityTypology createFacilityTypology() {
        return new FacilityTypology();
    }

    /**
     * Create an instance of {@link CancellationPolicy }
     * 
     */
    public CancellationPolicy createCancellationPolicy() {
        return new CancellationPolicy();
    }

    /**
     * Create an instance of {@link GroupZones }
     * 
     */
    public GroupZones createGroupZones() {
        return new GroupZones();
    }

    /**
     * Create an instance of {@link AvailabilityRQ }
     * 
     */
    public AvailabilityRQ createAvailabilityRQ() {
        return new AvailabilityRQ();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link InterestPoint }
     * 
     */
    public InterestPoint createInterestPoint() {
        return new InterestPoint();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link PaxBooking }
     * 
     */
    public PaxBooking createPaxBooking() {
        return new PaxBooking();
    }

    /**
     * Create an instance of {@link CheckRateRQ }
     * 
     */
    public CheckRateRQ createCheckRateRQ() {
        return new CheckRateRQ();
    }

    /**
     * Create an instance of {@link ChainsRS }
     * 
     */
    public ChainsRS createChainsRS() {
        return new ChainsRS();
    }

    /**
     * Create an instance of {@link RateComment }
     * 
     */
    public RateComment createRateComment() {
        return new RateComment();
    }

    /**
     * Create an instance of {@link BookingRS }
     * 
     */
    public BookingRS createBookingRS() {
        return new BookingRS();
    }

    /**
     * Create an instance of {@link Segments }
     * 
     */
    public Segments createSegments() {
        return new Segments();
    }

    /**
     * Create an instance of {@link Countries }
     * 
     */
    public Countries createCountries() {
        return new Countries();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link Holder }
     * 
     */
    public Holder createHolder() {
        return new Holder();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link InvoiceCompany }
     * 
     */
    public InvoiceCompany createInvoiceCompany() {
        return new InvoiceCompany();
    }

    /**
     * Create an instance of {@link ReviewsSelector }
     * 
     */
    public ReviewsSelector createReviewsSelector() {
        return new ReviewsSelector();
    }

    /**
     * Create an instance of {@link OccupanciesSelector }
     * 
     */
    public OccupanciesSelector createOccupanciesSelector() {
        return new OccupanciesSelector();
    }

    /**
     * Create an instance of {@link HotelIssue }
     * 
     */
    public HotelIssue createHotelIssue() {
        return new HotelIssue();
    }

    /**
     * Create an instance of {@link CommentByRates }
     * 
     */
    public CommentByRates createCommentByRates() {
        return new CommentByRates();
    }

    /**
     * Create an instance of {@link Chain }
     * 
     */
    public Chain createChain() {
        return new Chain();
    }

    /**
     * Create an instance of {@link CountriesRS }
     * 
     */
    public CountriesRS createCountriesRS() {
        return new CountriesRS();
    }

    /**
     * Create an instance of {@link RatePromotion }
     * 
     */
    public RatePromotion createRatePromotion() {
        return new RatePromotion();
    }

    /**
     * Create an instance of {@link Destinations }
     * 
     */
    public Destinations createDestinations() {
        return new Destinations();
    }

    /**
     * Create an instance of {@link RoomCheckrateRequest }
     * 
     */
    public RoomCheckrateRequest createRoomCheckrateRequest() {
        return new RoomCheckrateRequest();
    }

    /**
     * Create an instance of {@link FacilityGroupsRS }
     * 
     */
    public FacilityGroupsRS createFacilityGroupsRS() {
        return new FacilityGroupsRS();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link Boards }
     * 
     */
    public Boards createBoards() {
        return new Boards();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Board }
     * 
     */
    public Board createBoard() {
        return new Board();
    }

    /**
     * Create an instance of {@link Zones }
     * 
     */
    public Zones createZones() {
        return new Zones();
    }

    /**
     * Create an instance of {@link PaxesBooking }
     * 
     */
    public PaxesBooking createPaxesBooking() {
        return new PaxesBooking();
    }

    /**
     * Create an instance of {@link DestinationSelector }
     * 
     */
    public DestinationSelector createDestinationSelector() {
        return new DestinationSelector();
    }

    /**
     * Create an instance of {@link RoomSelector }
     * 
     */
    public RoomSelector createRoomSelector() {
        return new RoomSelector();
    }

    /**
     * Create an instance of {@link HotelBookingResponse }
     * 
     */
    public HotelBookingResponse createHotelBookingResponse() {
        return new HotelBookingResponse();
    }

    /**
     * Create an instance of {@link RoomsStatic }
     * 
     */
    public RoomsStatic createRoomsStatic() {
        return new RoomsStatic();
    }

    /**
     * Create an instance of {@link FacilityGroups }
     * 
     */
    public FacilityGroups createFacilityGroups() {
        return new FacilityGroups();
    }

    /**
     * Create an instance of {@link BookingResponse }
     * 
     */
    public BookingResponse createBookingResponse() {
        return new BookingResponse();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link RateHotelResponse }
     * 
     */
    public RateHotelResponse createRateHotelResponse() {
        return new RateHotelResponse();
    }

}
