//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.17 at 10:54:05 AM ICT 
//


package com.sabre.schema.sp.reservation.v2_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PricingProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingProviderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProviderName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PricingOptions" type="{http://services.sabre.com/sp/reservation/v2_4}PricingRequestInformationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingProviderType", propOrder = {
    "providerName",
    "pricingOptions"
})
public class PricingProviderType {

    @XmlElement(name = "ProviderName", required = true)
    protected String providerName;
    @XmlElement(name = "PricingOptions")
    protected PricingRequestInformationType pricingOptions;

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    /**
     * Gets the value of the pricingOptions property.
     * 
     * @return
     *     possible object is
     *     {@link PricingRequestInformationType }
     *     
     */
    public PricingRequestInformationType getPricingOptions() {
        return pricingOptions;
    }

    /**
     * Sets the value of the pricingOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricingRequestInformationType }
     *     
     */
    public void setPricingOptions(PricingRequestInformationType value) {
        this.pricingOptions = value;
    }

}
