//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 12:36:19 AM ICT 
//


package com.sabre.schema.hotel.avail.v4_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  Hotel Image Informataion
 * 
 * <p>Java class for HotelImageInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelImageInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ImageItem" type="{http://services.sabre.com/hotel/avail/v4_0_0}ImageItem" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelImageInfo", propOrder = {
    "imageItem"
})
public class HotelImageInfo {

    @XmlElement(name = "ImageItem")
    protected ImageItem imageItem;

    /**
     * Gets the value of the imageItem property.
     * 
     * @return
     *     possible object is
     *     {@link ImageItem }
     *     
     */
    public ImageItem getImageItem() {
        return imageItem;
    }

    /**
     * Sets the value of the imageItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageItem }
     *     
     */
    public void setImageItem(ImageItem value) {
        this.imageItem = value;
    }

}
