//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 12:36:19 AM ICT 
//


package com.sabre.schema.hotel.avail.v4_0_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *  Hotel Image item details
 * 
 * <p>Java class for ImageItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Image" type="{http://services.sabre.com/hotel/avail/v4_0_0}Image"/&gt;
 *         &lt;element name="Category" type="{http://services.sabre.com/hotel/avail/v4_0_0}Category"/&gt;
 *         &lt;element name="AdditionalInfo" type="{http://services.sabre.com/hotel/avail/v4_0_0}AdditionalInfo"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" use="required" type="{http://services.sabre.com/hotel/avail/v4_0_0}StringLength0to255" /&gt;
 *       &lt;attribute name="Ordinal" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="Format" use="required" type="{http://services.sabre.com/hotel/avail/v4_0_0}ImageFormats" /&gt;
 *       &lt;attribute name="LastModifedDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageItem", propOrder = {
    "image",
    "category",
    "additionalInfo"
})
public class ImageItem {

    @XmlElement(name = "Image", required = true)
    protected Image image;
    @XmlElement(name = "Category", required = true)
    protected Category category;
    @XmlElement(name = "AdditionalInfo", required = true)
    protected AdditionalInfo additionalInfo;
    @XmlAttribute(name = "Id", required = true)
    protected String id;
    @XmlAttribute(name = "Ordinal", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger ordinal;
    @XmlAttribute(name = "Format", required = true)
    protected ImageFormats format;
    @XmlAttribute(name = "LastModifedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastModifedDate;

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Image }
     *     
     */
    public Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image }
     *     
     */
    public void setImage(Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfo }
     *     
     */
    public AdditionalInfo getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfo }
     *     
     */
    public void setAdditionalInfo(AdditionalInfo value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the ordinal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrdinal() {
        return ordinal;
    }

    /**
     * Sets the value of the ordinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrdinal(BigInteger value) {
        this.ordinal = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link ImageFormats }
     *     
     */
    public ImageFormats getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageFormats }
     *     
     */
    public void setFormat(ImageFormats value) {
        this.format = value;
    }

    /**
     * Gets the value of the lastModifedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifedDate() {
        return lastModifedDate;
    }

    /**
     * Sets the value of the lastModifedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifedDate(XMLGregorianCalendar value) {
        this.lastModifedDate = value;
    }

}
