//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 12:36:19 AM ICT 
//


package com.sabre.schema.hotel.avail.v4_0_0;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RateTaxesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateTaxesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Tax" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="StartDate" type="{http://services.sabre.com/hotel/avail/v4_0_0}Date" /&gt;
 *                 &lt;attribute name="EndDate" type="{http://services.sabre.com/hotel/avail/v4_0_0}Date" /&gt;
 *                 &lt;attribute name="Amount" use="required" type="{http://services.sabre.com/hotel/avail/v4_0_0}Amount" /&gt;
 *                 &lt;attribute name="CurrencyCode" use="required" type="{http://services.sabre.com/hotel/avail/v4_0_0}StringLength3WithNoSpace" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TaxGroups" type="{http://services.sabre.com/hotel/avail/v4_0_0}TaxGroupsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Amount" type="{http://services.sabre.com/hotel/avail/v4_0_0}Amount" /&gt;
 *       &lt;attribute name="CurrencyCode" type="{http://services.sabre.com/hotel/avail/v4_0_0}StringLength3WithNoSpace" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateTaxesType", propOrder = {
    "taxes",
    "taxGroups"
})
public class RateTaxesType {

    @XmlElement(name = "Tax")
    protected List<RateTaxesType.Tax> taxes;
    @XmlElement(name = "TaxGroups")
    protected TaxGroupsType taxGroups;
    @XmlAttribute(name = "Amount")
    protected BigDecimal amount;
    @XmlAttribute(name = "CurrencyCode")
    protected String currencyCode;

    /**
     * Gets the value of the taxes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateTaxesType.Tax }
     * 
     * 
     */
    public List<RateTaxesType.Tax> getTaxes() {
        if (taxes == null) {
            taxes = new ArrayList<RateTaxesType.Tax>();
        }
        return this.taxes;
    }

    /**
     * Gets the value of the taxGroups property.
     * 
     * @return
     *     possible object is
     *     {@link TaxGroupsType }
     *     
     */
    public TaxGroupsType getTaxGroups() {
        return taxGroups;
    }

    /**
     * Sets the value of the taxGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxGroupsType }
     *     
     */
    public void setTaxGroups(TaxGroupsType value) {
        this.taxGroups = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }


    /**
     * Represents a tax type applicable.
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="StartDate" type="{http://services.sabre.com/hotel/avail/v4_0_0}Date" /&gt;
     *       &lt;attribute name="EndDate" type="{http://services.sabre.com/hotel/avail/v4_0_0}Date" /&gt;
     *       &lt;attribute name="Amount" use="required" type="{http://services.sabre.com/hotel/avail/v4_0_0}Amount" /&gt;
     *       &lt;attribute name="CurrencyCode" use="required" type="{http://services.sabre.com/hotel/avail/v4_0_0}StringLength3WithNoSpace" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Tax {

        @XmlAttribute(name = "StartDate")
        protected XMLGregorianCalendar startDate;
        @XmlAttribute(name = "EndDate")
        protected XMLGregorianCalendar endDate;
        @XmlAttribute(name = "Amount", required = true)
        protected BigDecimal amount;
        @XmlAttribute(name = "CurrencyCode", required = true)
        protected String currencyCode;

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyCode() {
            return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyCode(String value) {
            this.currencyCode = value;
        }

    }

}
