//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 10:14:00 PM ICT 
//


package com.sabre.schema.hotel.details.v3_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 RateInfos - Collection of Rate information for a request from all suppliers. TotalRates (not
 *                 room specific)
 *             
 * 
 * <p>Java class for HotelRateInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelRateInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RateInfos" type="{http://services.sabre.com/hotel/details/v3_0_0}RateInfosType"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Rooms" type="{http://services.sabre.com/hotel/details/v3_0_0}Rooms" minOccurs="0"/&gt;
 *           &lt;element name="RoomSets" type="{http://services.sabre.com/hotel/details/v3_0_0}RoomSetsType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelRateInfoType", propOrder = {
    "rateInfos",
    "roomSets",
    "rooms"
})
public class HotelRateInfoType {

    @XmlElement(name = "RateInfos", required = true)
    protected RateInfosType rateInfos;
    @XmlElement(name = "RoomSets")
    protected RoomSetsType roomSets;
    @XmlElement(name = "Rooms")
    protected Rooms rooms;

    /**
     * Gets the value of the rateInfos property.
     * 
     * @return
     *     possible object is
     *     {@link RateInfosType }
     *     
     */
    public RateInfosType getRateInfos() {
        return rateInfos;
    }

    /**
     * Sets the value of the rateInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateInfosType }
     *     
     */
    public void setRateInfos(RateInfosType value) {
        this.rateInfos = value;
    }

    /**
     * Gets the value of the roomSets property.
     * 
     * @return
     *     possible object is
     *     {@link RoomSetsType }
     *     
     */
    public RoomSetsType getRoomSets() {
        return roomSets;
    }

    /**
     * Sets the value of the roomSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomSetsType }
     *     
     */
    public void setRoomSets(RoomSetsType value) {
        this.roomSets = value;
    }

    /**
     * Gets the value of the rooms property.
     * 
     * @return
     *     possible object is
     *     {@link Rooms }
     *     
     */
    public Rooms getRooms() {
        return rooms;
    }

    /**
     * Sets the value of the rooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rooms }
     *     
     */
    public void setRooms(Rooms value) {
        this.rooms = value;
    }

}
