//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 10:14:00 PM ICT 
//


package com.sabre.schema.hotel.details.v3_0_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Panoramic Medias
 * 
 * <p>Java class for PanoramicMedias complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PanoramicMedias"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="5" minOccurs="0"&gt;
 *         &lt;element name="PanoramicMedia"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="Type" use="required" type="{http://services.sabre.com/hotel/details/v3_0_0}PanoramaMediaTypes" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "details", name = "PanoramicMedias", propOrder = {
    "panoramicMedias"
})
public class PanoramicMedias {

    @XmlElement(name = "PanoramicMedia")
    protected List<PanoramicMedias.PanoramicMedia> panoramicMedias;

    /**
     * Gets the value of the panoramicMedias property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the panoramicMedias property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPanoramicMedias().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PanoramicMedias.PanoramicMedia }
     *
     *
     */
    public List<PanoramicMedias.PanoramicMedia> getPanoramicMedias() {
        if (panoramicMedias == null) {
            panoramicMedias = new ArrayList<PanoramicMedias.PanoramicMedia>();
        }
        return this.panoramicMedias;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="Type" use="required" type="{http://services.sabre.com/hotel/details/v3_0_0}PanoramaMediaTypes" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PanoramicMedia {

        @XmlAttribute(name = "Type", required = true)
        protected PanoramaMediaTypes type;

        /**
         * Gets the value of the type property.
         *
         * @return
         *     possible object is
         *     {@link PanoramaMediaTypes }
         *
         */
        public PanoramaMediaTypes getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value
         *     allowed object is
         *     {@link PanoramaMediaTypes }
         *     
         */
        public void setType(PanoramaMediaTypes value) {
            this.type = value;
        }

    }

}
