//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 10:14:00 PM ICT 
//


package com.sabre.schema.hotel.details.v3_0_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Collection of Rate information for a request from all suppliers.
 *             
 * 
 * <p>Java class for RateInfosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateInfosType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RateInfo" type="{http://services.sabre.com/hotel/details/v3_0_0}RateInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ConvertedRateInfo" type="{http://services.sabre.com/hotel/details/v3_0_0}RateInfoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ShopKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateInfosType", propOrder = {
    "rateInfos",
    "convertedRateInfos"
})
public class RateInfosType {

    @XmlElement(name = "RateInfo")
    protected List<RateInfoType> rateInfos;
    @XmlElement(name = "ConvertedRateInfo")
    protected List<RateInfoType> convertedRateInfos;
    @XmlAttribute(name = "ShopKey")
    protected String shopKey;

    /**
     * Gets the value of the rateInfos property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateInfos property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateInfos().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateInfoType }
     *
     *
     */
    public List<RateInfoType> getRateInfos() {
        if (rateInfos == null) {
            rateInfos = new ArrayList<RateInfoType>();
        }
        return this.rateInfos;
    }

    /**
     * Gets the value of the convertedRateInfos property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the convertedRateInfos property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConvertedRateInfos().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateInfoType }
     *
     *
     */
    public List<RateInfoType> getConvertedRateInfos() {
        if (convertedRateInfos == null) {
            convertedRateInfos = new ArrayList<RateInfoType>();
        }
        return this.convertedRateInfos;
    }

    /**
     * Gets the value of the shopKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * Sets the value of the shopKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopKey(String value) {
        this.shopKey = value;
    }

}
