//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 12:36:19 AM ICT 
//


package com.sabre.schema.hotel.content.v4_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes hotel content including images for a list of hotels .
 * 
 * <p>Java class for HotelContentInfos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotelContentInfos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="HotelContentInfo" type="{http://services.sabre.com/hotel/content/v4_0_0}HotelContentInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelContentInfos", propOrder = {
    "hotelContentInfo"
})
public class HotelContentInfos {

    @XmlElement(name = "HotelContentInfo")
    protected HotelContentInfo hotelContentInfo;

    /**
     * Gets the value of the hotelContentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link HotelContentInfo }
     *     
     */
    public HotelContentInfo getHotelContentInfo() {
        return hotelContentInfo;
    }

    /**
     * Sets the value of the hotelContentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelContentInfo }
     *     
     */
    public void setHotelContentInfo(HotelContentInfo value) {
        this.hotelContentInfo = value;
    }

}
