//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 12:36:19 AM ICT 
//


package com.sabre.schema.hotel.content.v4_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specify the media types and other parameters of MediaItems to be returned.
 * 
 * <p>Java class for MediaRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaRef"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="MediaTypes" type="{http://services.sabre.com/hotel/content/v4_0_0}MediaTypes" minOccurs="0"/&gt;
 *         &lt;element name="Categories" type="{http://services.sabre.com/hotel/content/v4_0_0}Categories" minOccurs="0"/&gt;
 *         &lt;element name="RoomTypeCodes" type="{http://services.sabre.com/hotel/content/v4_0_0}RoomTypeCodes" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalInfo" type="{http://services.sabre.com/hotel/content/v4_0_0}AdditionalInfoRef" minOccurs="0"/&gt;
 *         &lt;element name="Languages" type="{http://services.sabre.com/hotel/content/v4_0_0}Languages" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="MaxItems" type="{http://services.sabre.com/hotel/content/v4_0_0}MaxImagesType" default="1" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaRef", propOrder = {
    "mediaTypes",
    "categories",
    "roomTypeCodes",
    "additionalInfo",
    "languages"
})
public class MediaRef {

    @XmlElement(name = "MediaTypes")
    protected MediaTypes mediaTypes;
    @XmlElement(name = "Categories")
    protected Categories categories;
    @XmlElement(name = "RoomTypeCodes")
    protected RoomTypeCodes roomTypeCodes;
    @XmlElement(name = "AdditionalInfo")
    protected AdditionalInfoRef additionalInfo;
    @XmlElement(name = "Languages")
    protected Languages languages;
    @XmlAttribute(name = "MaxItems")
    protected String maxItems;

    /**
     * Gets the value of the mediaTypes property.
     * 
     * @return
     *     possible object is
     *     {@link MediaTypes }
     *     
     */
    public MediaTypes getMediaTypes() {
        return mediaTypes;
    }

    /**
     * Sets the value of the mediaTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaTypes }
     *     
     */
    public void setMediaTypes(MediaTypes value) {
        this.mediaTypes = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link Categories }
     *     
     */
    public Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Categories }
     *     
     */
    public void setCategories(Categories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the roomTypeCodes property.
     * 
     * @return
     *     possible object is
     *     {@link RoomTypeCodes }
     *     
     */
    public RoomTypeCodes getRoomTypeCodes() {
        return roomTypeCodes;
    }

    /**
     * Sets the value of the roomTypeCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomTypeCodes }
     *     
     */
    public void setRoomTypeCodes(RoomTypeCodes value) {
        this.roomTypeCodes = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfoRef }
     *     
     */
    public AdditionalInfoRef getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfoRef }
     *     
     */
    public void setAdditionalInfo(AdditionalInfoRef value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link Languages }
     *     
     */
    public Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languages }
     *     
     */
    public void setLanguages(Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the maxItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxItems() {
        if (maxItems == null) {
            return "1";
        } else {
            return maxItems;
        }
    }

    /**
     * Sets the value of the maxItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxItems(String value) {
        this.maxItems = value;
    }

}
