//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.07 at 12:36:19 AM ICT 
//


package com.sabre.schema.hotel.content.v4_0_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sabre.services.hotel.content.v4_0_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sabre.services.hotel.content.v4_0_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImageContentDescription }
     * 
     */
    public ImageContentDescription createImageContentDescription() {
        return new ImageContentDescription();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.Description }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.Description createDescription() {
        return new com.sabre.schema.hotel.content.v4_0_0.Description();
    }

    /**
     * Create an instance of {@link DescriptionInfo }
     * 
     */
    public DescriptionInfo createDescriptionInfo() {
        return new DescriptionInfo();
    }

    /**
     * Create an instance of {@link Neighborhoods }
     * 
     */
    public Neighborhoods createNeighborhoods() {
        return new Neighborhoods();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PropertyTypeInfo }
     * 
     */
    public PropertyTypeInfo createPropertyTypeInfo() {
        return new PropertyTypeInfo();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link PropertyQualityInfo }
     * 
     */
    public PropertyQualityInfo createPropertyQualityInfo() {
        return new PropertyQualityInfo();
    }

    /**
     * Create an instance of {@link Videos }
     * 
     */
    public Videos createVideos() {
        return new Videos();
    }

    /**
     * Create an instance of {@link PanoramicMedias }
     * 
     */
    public PanoramicMedias createPanoramicMedias() {
        return new PanoramicMedias();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link Languages }
     * 
     */
    public Languages createLanguages() {
        return new Languages();
    }

    /**
     * Create an instance of {@link AdditionalInfoRef }
     * 
     */
    public AdditionalInfoRef createAdditionalInfoRef() {
        return new AdditionalInfoRef();
    }

    /**
     * Create an instance of {@link RoomTypeCodes }
     * 
     */
    public RoomTypeCodes createRoomTypeCodes() {
        return new RoomTypeCodes();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link DescriptionsRef }
     * 
     */
    public DescriptionsRef createDescriptionsRef() {
        return new DescriptionsRef();
    }

    /**
     * Create an instance of {@link POS }
     * 
     */
    public POS createPOS() {
        return new POS();
    }

    /**
     * Create an instance of {@link GetHotelContentRQ }
     * 
     */
    public GetHotelContentRQ createGetHotelContentRQ() {
        return new GetHotelContentRQ();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link GetHotelContentRS }
     * 
     */
    public GetHotelContentRS createGetHotelContentRS() {
        return new GetHotelContentRS();
    }

    /**
     * Create an instance of {@link HotelContentInfos }
     * 
     */
    public HotelContentInfos createHotelContentInfos() {
        return new HotelContentInfos();
    }

    /**
     * Create an instance of {@link HotelRef }
     * 
     */
    public HotelRef createHotelRef() {
        return new HotelRef();
    }

    /**
     * Create an instance of {@link DescriptiveInfoRef }
     * 
     */
    public DescriptiveInfoRef createDescriptiveInfoRef() {
        return new DescriptiveInfoRef();
    }

    /**
     * Create an instance of {@link MediaRef }
     * 
     */
    public MediaRef createMediaRef() {
        return new MediaRef();
    }

    /**
     * Create an instance of {@link MediaTypes }
     * 
     */
    public MediaTypes createMediaTypes() {
        return new MediaTypes();
    }

    /**
     * Create an instance of {@link HotelInfo }
     * 
     */
    public HotelInfo createHotelInfo() {
        return new HotelInfo();
    }

    /**
     * Create an instance of {@link TierLabels }
     * 
     */
    public TierLabels createTierLabels() {
        return new TierLabels();
    }

    /**
     * Create an instance of {@link TierLabel }
     * 
     */
    public TierLabel createTierLabel() {
        return new TierLabel();
    }

    /**
     * Create an instance of {@link PropertyTypes }
     * 
     */
    public PropertyTypes createPropertyTypes() {
        return new PropertyTypes();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.PropertyType }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.PropertyType createPropertyType() {
        return new com.sabre.schema.hotel.content.v4_0_0.PropertyType();
    }

    /**
     * Create an instance of {@link HotelDescriptiveInfo }
     * 
     */
    public HotelDescriptiveInfo createHotelDescriptiveInfo() {
        return new HotelDescriptiveInfo();
    }

    /**
     * Create an instance of {@link PropertyInfo }
     * 
     */
    public PropertyInfo createPropertyInfo() {
        return new PropertyInfo();
    }

    /**
     * Create an instance of {@link Policies }
     * 
     */
    public Policies createPolicies() {
        return new Policies();
    }

    /**
     * Create an instance of {@link LocationInfo }
     * 
     */
    public LocationInfo createLocationInfo() {
        return new LocationInfo();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Amenities }
     * 
     */
    public Amenities createAmenities() {
        return new Amenities();
    }

    /**
     * Create an instance of {@link Amenity }
     * 
     */
    public Amenity createAmenity() {
        return new Amenity();
    }

    /**
     * Create an instance of {@link Descriptions }
     * 
     */
    public Descriptions createDescriptions() {
        return new Descriptions();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.Info }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.Info createInfo() {
        return new com.sabre.schema.hotel.content.v4_0_0.Info();
    }

    /**
     * Create an instance of {@link AdditionalInfo }
     * 
     */
    public AdditionalInfo createAdditionalInfo() {
        return new AdditionalInfo();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.Category }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.Category createCategory() {
        return new com.sabre.schema.hotel.content.v4_0_0.Category();
    }

    /**
     * Create an instance of {@link HotelMediaInfo }
     * 
     */
    public HotelMediaInfo createHotelMediaInfo() {
        return new HotelMediaInfo();
    }

    /**
     * Create an instance of {@link MediaItems }
     * 
     */
    public MediaItems createMediaItems() {
        return new MediaItems();
    }

    /**
     * Create an instance of {@link MediaItem }
     * 
     */
    public MediaItem createMediaItem() {
        return new MediaItem();
    }

    /**
     * Create an instance of {@link PanoramicMediasItems }
     * 
     */
    public PanoramicMediasItems createPanoramicMediasItems() {
        return new PanoramicMediasItems();
    }

    /**
     * Create an instance of {@link VideosItems }
     * 
     */
    public VideosItems createVideosItems() {
        return new VideosItems();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.RoomTypeCode }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.RoomTypeCode createRoomTypeCode() {
        return new com.sabre.schema.hotel.content.v4_0_0.RoomTypeCode();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.PanoramicMedia }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.PanoramicMedia createPanoramicMedia() {
        return new com.sabre.schema.hotel.content.v4_0_0.PanoramicMedia();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.Video }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.Video createVideo() {
        return new com.sabre.schema.hotel.content.v4_0_0.Video();
    }

    /**
     * Create an instance of {@link ImageItems }
     * 
     */
    public ImageItems createImageItems() {
        return new ImageItems();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.Image }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.Image createImage() {
        return new com.sabre.schema.hotel.content.v4_0_0.Image();
    }

    /**
     * Create an instance of {@link SecurityFeatureInfos }
     * 
     */
    public SecurityFeatureInfos createSecurityFeatureInfos() {
        return new SecurityFeatureInfos();
    }

    /**
     * Create an instance of {@link SecurityFeature }
     * 
     */
    public SecurityFeature createSecurityFeature() {
        return new SecurityFeature();
    }

    /**
     * Create an instance of {@link HotelRefs }
     * 
     */
    public HotelRefs createHotelRefs() {
        return new HotelRefs();
    }

    /**
     * Create an instance of {@link HotelContentInfo }
     * 
     */
    public HotelContentInfo createHotelContentInfo() {
        return new HotelContentInfo();
    }

    /**
     * Create an instance of {@link ImageContentDescription.Text }
     * 
     */
    public ImageContentDescription.Text createImageContentDescriptionText() {
        return new ImageContentDescription.Text();
    }

    /**
     * Create an instance of {@link com.sabre.schema.hotel.content.v4_0_0.Description.Text }
     * 
     */
    public com.sabre.schema.hotel.content.v4_0_0.Description.Text createDescriptionText() {
        return new com.sabre.schema.hotel.content.v4_0_0.Description.Text();
    }

    /**
     * Create an instance of {@link DescriptionInfo.Text }
     * 
     */
    public DescriptionInfo.Text createDescriptionInfoText() {
        return new DescriptionInfo.Text();
    }

    /**
     * Create an instance of {@link Neighborhoods.Neighborhood }
     * 
     */
    public Neighborhoods.Neighborhood createNeighborhoodsNeighborhood() {
        return new Neighborhoods.Neighborhood();
    }

    /**
     * Create an instance of {@link Address.CityName }
     * 
     */
    public Address.CityName createAddressCityName() {
        return new Address.CityName();
    }

    /**
     * Create an instance of {@link Address.StateProv }
     * 
     */
    public Address.StateProv createAddressStateProv() {
        return new Address.StateProv();
    }

    /**
     * Create an instance of {@link Address.CountryName }
     * 
     */
    public Address.CountryName createAddressCountryName() {
        return new Address.CountryName();
    }

    /**
     * Create an instance of {@link PropertyTypeInfo.PropertyType }
     * 
     */
    public PropertyTypeInfo.PropertyType createPropertyTypeInfoPropertyType() {
        return new PropertyTypeInfo.PropertyType();
    }

    /**
     * Create an instance of {@link Policy.Text }
     * 
     */
    public Policy.Text createPolicyText() {
        return new Policy.Text();
    }

    /**
     * Create an instance of {@link PropertyQualityInfo.PropertyQuality }
     * 
     */
    public PropertyQualityInfo.PropertyQuality createPropertyQualityInfoPropertyQuality() {
        return new PropertyQualityInfo.PropertyQuality();
    }

    /**
     * Create an instance of {@link Videos.Video }
     * 
     */
    public Videos.Video createVideosVideo() {
        return new Videos.Video();
    }

    /**
     * Create an instance of {@link PanoramicMedias.PanoramicMedia }
     * 
     */
    public PanoramicMedias.PanoramicMedia createPanoramicMediasPanoramicMedia() {
        return new PanoramicMedias.PanoramicMedia();
    }

    /**
     * Create an instance of {@link Images.Image }
     * 
     */
    public Images.Image createImagesImage() {
        return new Images.Image();
    }

    /**
     * Create an instance of {@link Languages.Language }
     * 
     */
    public Languages.Language createLanguagesLanguage() {
        return new Languages.Language();
    }

    /**
     * Create an instance of {@link AdditionalInfoRef.Info }
     * 
     */
    public AdditionalInfoRef.Info createAdditionalInfoRefInfo() {
        return new AdditionalInfoRef.Info();
    }

    /**
     * Create an instance of {@link RoomTypeCodes.RoomTypeCode }
     * 
     */
    public RoomTypeCodes.RoomTypeCode createRoomTypeCodesRoomTypeCode() {
        return new RoomTypeCodes.RoomTypeCode();
    }

    /**
     * Create an instance of {@link Categories.Category }
     * 
     */
    public Categories.Category createCategoriesCategory() {
        return new Categories.Category();
    }

    /**
     * Create an instance of {@link DescriptionsRef.Description }
     * 
     */
    public DescriptionsRef.Description createDescriptionsRefDescription() {
        return new DescriptionsRef.Description();
    }

    /**
     * Create an instance of {@link POS.Source }
     * 
     */
    public POS.Source createPOSSource() {
        return new POS.Source();
    }

}
