//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.02 at 02:55:47 PM ICT 
//


package com.traveltek.schemas.messages;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="arrivedate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="arrivetime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="day" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="departdate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="departtime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="idlcrossed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orderid" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="originalitineraryname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ownerid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="portid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shortdescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="supered_id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="categoryid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="facilityid" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="facilitytypeid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "item")
public class Item {

    @XmlAttribute
    protected String arrivedate;
    @XmlAttribute
    protected String arrivetime;
    @XmlAttribute
    protected BigInteger day;
    @XmlAttribute
    protected String departdate;
    @XmlAttribute
    protected String departtime;
    @XmlAttribute
    protected String description;
    @XmlAttribute
    protected String idlcrossed;
    @XmlAttribute
    protected BigDecimal latitude;
    @XmlAttribute
    protected BigDecimal longitude;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected BigInteger orderid;
    @XmlAttribute
    protected String originalitineraryname;
    @XmlAttribute
    protected String ownerid;
    @XmlAttribute
    protected String portid;
    @XmlAttribute
    protected String shortdescription;
    @XmlAttribute(name = "supered_id")
    protected BigInteger superedId;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected String categoryid;
    @XmlAttribute
    protected BigInteger facilityid;
    @XmlAttribute
    protected String facilitytypeid;
    @XmlAttribute
    protected String quantity;

    /**
     * Gets the value of the arrivedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivedate() {
        return arrivedate;
    }

    /**
     * Sets the value of the arrivedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivedate(String value) {
        this.arrivedate = value;
    }

    /**
     * Gets the value of the arrivetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivetime() {
        return arrivetime;
    }

    /**
     * Sets the value of the arrivetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivetime(String value) {
        this.arrivetime = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDay(BigInteger value) {
        this.day = value;
    }

    /**
     * Gets the value of the departdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartdate() {
        return departdate;
    }

    /**
     * Sets the value of the departdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartdate(String value) {
        this.departdate = value;
    }

    /**
     * Gets the value of the departtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeparttime() {
        return departtime;
    }

    /**
     * Sets the value of the departtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeparttime(String value) {
        this.departtime = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the idlcrossed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdlcrossed() {
        return idlcrossed;
    }

    /**
     * Sets the value of the idlcrossed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdlcrossed(String value) {
        this.idlcrossed = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the orderid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderid() {
        return orderid;
    }

    /**
     * Sets the value of the orderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderid(BigInteger value) {
        this.orderid = value;
    }

    /**
     * Gets the value of the originalitineraryname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalitineraryname() {
        return originalitineraryname;
    }

    /**
     * Sets the value of the originalitineraryname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalitineraryname(String value) {
        this.originalitineraryname = value;
    }

    /**
     * Gets the value of the ownerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     * Sets the value of the ownerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerid(String value) {
        this.ownerid = value;
    }

    /**
     * Gets the value of the portid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortid() {
        return portid;
    }

    /**
     * Sets the value of the portid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortid(String value) {
        this.portid = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdescription(String value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the superedId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuperedId() {
        return superedId;
    }

    /**
     * Sets the value of the superedId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuperedId(BigInteger value) {
        this.superedId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the categoryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * Sets the value of the categoryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryid(String value) {
        this.categoryid = value;
    }

    /**
     * Gets the value of the facilityid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFacilityid() {
        return facilityid;
    }

    /**
     * Sets the value of the facilityid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFacilityid(BigInteger value) {
        this.facilityid = value;
    }

    /**
     * Gets the value of the facilitytypeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilitytypeid() {
        return facilitytypeid;
    }

    /**
     * Sets the value of the facilitytypeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilitytypeid(String value) {
        this.facilitytypeid = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

}
